# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='pipeline',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
